name: Build and deploy Flask app to Azure Web App - FreastyWeb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify a specific version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask flask-cors

      # Uncomment if you want to run tests
      # - name: Test application
      #   run: |
      #     pytest

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: Flask-app
          path: .  # Adjust if your app files are in a subdirectory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: Flask-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF9BD16EC8A24AA9A645AEB8CED9FEDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E4DE5162454F4D5CAA7AEDB72D42809F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_96E3A5399A234474A3004D2D6DB4A85F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FreastyWeb'
          package: .  # Adjust if necessary
          resource-group: 'Freasty_group'
